### ISSUE TITLE
desktop-onboarding-sign-up__form-note google-experiment

### ISSUE THREAD

**Issue by Salil-Jain** [Salil-sopho/memescraper#2]
Getting **desktop-onboarding-sign-up__form-note google-experiment** as `urls` variable instead of the next page's link in line 29 when number of pages is > 1

**Comment by dhicks43** [comment]
Hi, I just saw your project and I am interested in helping. Which version of python are you using? And would you be willing to use any libraries other than the ones included in your project?

**Comment by Salil-Jain** [comment]
Hey @dhicks43, thanks for your interest. The python version is 2.7.13.
I mostly refrain from using web scraping libraries in places where simple regex would do the work, other than that I am fine with using any library.

**Comment by Salil-Jain** [comment]
68c37fce4e4839507d433cb2ef232260f2f58778 solves it.
